main: net.enderbyteprograms.unihome.UniHomeMain
name: unihome
version: 1.0
api-version: 1.21

commands:
  sethome:
    description: Allows the user to set a home
    permission: unihome.use
  delhome:
    description: Allows the users to delete their home
    permission: unihome.use
  home:
    description: Allows the users to go home
    permission: unihome.use
  pvpon:
    description: Allow people to hit you
    permission: unihome.pvp
  pvpoff:
    description: Allow people to hit you
    permission: unihome.pvp
  getnearby:
    description: See players that are nearby
    permission: unihome.admin
  uhact:
    description: unihome administration commands
    permission: unihome.admin
  playtime:
    description: Playtime information about players
    permission: unihome.use
    aliases:
      - pt
  topplaytime:
    description: View the top 10 playtime leaderboard
    permission: unihome.use
    aliases:
      - toppt

permissions:
  unihome.use:
    default: true
  unihome.admin:
    default: op
  unihome.pvp:
    default: true