main: net.enderbyteprograms.UniHome.UniHomeMain
name: UniHome
version: 1.0
api-version: 1.21

commands:
  sethome:
    description: Allows the user to set a home
    permission: unihome.use
  delhome:
    description: Allows the users to delete their home
    permission: unihome.use
  home:
    description: Allows the users to go home
    permission: unihome.use
  pvpon:
    description: Allow people to hit you
    permission: unihome.pvp
  pvpoff:
    description: Allow people to hit you
    permission: unihome.pvp
  uhreload:
    description: Reload the Unihome plugin
    permission: unihome.admin

permissions:
  unihome.use:
    default: true
  unihome.admin:
    default: op
  unihome.pvp:
    default: true